### ISSUE TITLE
PHP Warning:  ksort() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by rolandinsh** [dockette/packagist#13]
Got error from the latest version
PHP Warning:  `ksort()` expects parameter 1 to be array, null given in /srv/src/Packagist/WebBundle/Package/SymlinkDumper.php on line 526

**Comment by f3l1x** [comment]
Hi, I hope it is just a warning. :-) I'd do nothing at this moment, yup?

**Comment by f3l1x** [comment]
Closing it. Feel free to open it again.
