### ISSUE TITLE
Is solr operational?

### ISSUE THREAD

**Issue by HadesArchitect** [dockette/packagist#2]
It looks like solr doesn't work or was manually configured.

**Comment by f3l1x** [comment]
You have to setup solr manually, especially create schema.

**Comment by HadesArchitect** [comment]
Any plans on documentation or adding automated/preconfigured solr?

**Comment by f3l1x** [comment]
It's in my roadmap. I don't have a time at this moment, I think maybe next week.

**Comment by f3l1x** [comment]
Closed via https://github.com/dockette/packagist/commit/48fd89c35a301c8b58f119a69f28900722036deb

**Comment by f3l1x** [comment]
@HadesArchitect Is it working for you now?
