### ISSUE TITLE
PHP: missing tokenizer extension

### ISSUE THREAD

**Issue by prhost** [dockette/packagist#4]
➜  packagist git:(master) ✗ docker-compose exec packagist /srv/app/console doctrine:schema:create

  [Symfony\Component\Debug\Exception\UndefinedFunctionException]
  Attempted to call function "token_get_all" from namespace "Doctrine\Common\Annotations".

doctrine:schema:create [--dump-sql] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

https://github.com/backbee/backbee-cms/issues/706

**Comment by f3l1x** [comment]
@prhost Hi. Thank you for the bugreport. You're right, tokenizer is missing. The AlpineLinux is constantly changing, I fix it as soon as possible. Or would you be able to prepare PR?

**Comment by prhost** [comment]
@f3l1x Sorry, I do not know how to do it, if I knew, I'd do it for you :/

**Comment by f3l1x** [comment]
@prhost Please let me known if it's working for you. Thank you. :wave:

**Comment by prhost** [comment]
Tokenizer is working, now appears another problem missing the extension simplexml, I will open a separate issue, I think it is better.
