### ISSUE TITLE
PHP: missing simplexml extension

### ISSUE THREAD

**Issue by prhost** [dockette/packagist#5]
[Symfony\Component\Debug\Exception\UndefinedFunctionException]
  Attempted to call function "simplexml_load_file" from namespace "Doctrine\ORM\Mapping\Driver".

http://stackoverflow.com/questions/35174592/call-to-undefined-function-doctrine-orm-mapping-driver-simplexml-load-file

:/

**Comment by f3l1x** [comment]
It should be fixed. Thank you again @prhost.
