### ISSUE TITLE
Can't clone with ssh protocol

### ISSUE THREAD

**Issue by nmartinez-nimeops** [dockette/packagist#9]
Hi, 
i'm trying private packagist, and it seems that we can't clone with ssh protocol ;)

> Failed to execute git clone --mirror 'ssh://git@(...snip...) .............
> fatal: cannot run ssh: No such file or directory fatal: unable to fork

**Comment by leopoiroux** [comment]
#10 resolved

**Comment by f3l1x** [comment]
@nimeops Could you test it again?

**Comment by nmartinez-nimeops** [comment]
I've forked and applied the same changes, its OK.
Have you updated docker images?

**Comment by f3l1x** [comment]
Yep. Cool. Thank you.
